path:
  main: '/home/v-yyeo/azurerm-development-automation'
  code: 'azurerm-development-automation'
  attachment: 'attachment'
  azurerm: '/home/v-yyeo/terraform-provider-azurerm-1/terraform-provider-azurerm'
  services: 'internal/services/desktopvirtualization'
  pandora: '/home/v-yyeo/pandora'
  sdk: '/home/v-yyeo/go-azure-sdk'
  locallyGeneratedSdk: '/home/v-yyeo/locally-generated-go-sdk'

defaultModel: 'claude-haiku-4.5'
# virtual_desktop_msix_package
# virtual_desktop_app_attach_package
# virtual_desktop_msix_image
# virtual_desktop_session_host
# virtual_desktop_application
resource: 'virtual_desktop_app_attach_package'
clientResource: ''
specification: 'https://github.com/Azure/azure-rest-api-specs/blob/main/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/DesktopVirtualization/stable/2025-10-10/desktopvirtualization.json'
serviceName: 'Desktop Virtualization'
pandoraServiceName: ''
port:
  dataApi: 8083
  httpProxy: 8084
  httpProxyListener: 8085

# registration2PortalProperty
# Check if properties returned are correct
# schema
# Set property default
# crud2BasicTest
# Check if `TestAcc{pascalCaseResource}_basic` makes sense
# basicTest
# Fix `TestAcc{pascalCaseResource}_basic`
# completeTest
# Fix `TestAcc{pascalCaseResource}_complete`
# validateFunc
# Check if `ValidateFunc` is applied correctly
# maxItems
# Check if `MaxItems` is applied correctly
# forceNew
# Check if `ForceNew` is applied correctly

# flattenProperty
# property2Required
# generateProperty
# generateAttribute
flow: 'crud2BasicTest'