path:
  main: '/home/v-yyeo/azurerm-development-automation'
  code: 'azurerm-development-automation'
  attachment: 'attachment'
  home: '/home/v-yyeo/'
  aiAssistedDevelopment: '/home/v-yyeo/.terraform-azurerm-ai-installer'
  terracorder: '/home/v-yyeo/terracorder'
  # Change below
  azurerm: '/home/v-yyeo/terraform-provider-azurerm-0/terraform-provider-azurerm'
  services: 'internal/services/communication'
  # Change above
  document: 'website/docs'
  pandora: '/home/v-yyeo/pandora'
  sdk: '/home/v-yyeo/go-azure-sdk'
  locallyGeneratedSdk: '/home/v-yyeo/locally-generated-go-sdk'

defaultModel: 'claude-haiku-4.5'
resource: 'communication_service'
clientResource: ''
specification: 'https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/resource-manager/Microsoft.Communication/stable/2026-03-18/openapi.json'
clientServiceName: 'Communication'
pandoraService: ''
pandoraServiceName: 'Communication'
sdkServiceName: 'communication'
resourceGroupName: 'rg-yyeo-0'
nHttpProxy: 2
port:
  dataApi: 8083
  httpProxy:
    - sender: 8084
      listener: 8085
    - sender: 8086
      listener: 8087
    - sender: 8088
      listener: 8089
    - sender: 8090
      listener: 8091

# Take screenshots
# aiAssistedDevelopment2ReplaceDirective
# Run bumpApiVersion if necessary
# sdkImport2PortalProperty
# Check if properties returned are correct
# schema
# Set property default
# crud2BasicTest
# Check if `TestAcc{pascalCaseResource}_basic` makes sense
# basicTest
# Fix `TestAcc{pascalCaseResource}_basic`
# otherTest
# Fix `TestAcc{pascalCaseResource}_complete`
# validateFunc
# Check if `ValidateFunc` is applied correctly
# maxItems
# Check if `MaxItems` is applied correctly
# forceNew
# Check if `ForceNew` is applied correctly
# propertyPair
# Check if plan-time catch is needed
# runParallelTest
# Codes according to test results
# propertyName2ListResource
# Check if list resource test is correct
# document
# Check if document is correct
# fixCommand
# Check if fix command is correct
# Review with `terraform-azurerm-ai-assisted-development`
# prContent2TestRegex
# Create PR
# Run test in TeamCity
# tctest

# flattenProperty
# property2Required
# property
# attribute
# customizeDiff
# bumpApiVersion
flow: 'bumpApiVersion'

# validateFunc maxItems forceNew
referenceTest: 'translateRequiredQueryParametersDefault' # complete
generatedTestProperty:
  - 'translate_required_query_parameters'

# runParallelTest
testFileSuffix: '_resource_vf_test'
testRegex: '_\w*'

# changePropertyName
propertyNameMap:

# tctest
pr: '31317'
parallelism:

# flattenProperty
flattenParentProperty: 'image'

# property2Required
requiredProperty:
  - ''

# property
generatedProperty:
  - ''

# attribute
generatedAttribute:
  - ''

# bumpApiVersion
bBumpWithLocallyGeneratedSdk: true
