firstStep: GenerateResourceIdentity
step:
  GenerateCrud:
    input:
    - attachments:
      - /home/v-yyeo/azurerm-development-automation/attachment/virtual_desktop_msix_package/PreGenerateSdkOutput.json
      - /home/v-yyeo/azurerm-development-automation/attachment/virtual_desktop_msix_package/GenerateReplaceDirectiveOutput.json
      prompt: 'Generate CRUD methods in [virtual_desktop_msix_package_resource.go](/home/v-yyeo/terraform-provider-azurerm-2/terraform-provider-azurerm/internal/services/desktopvirtualization/virtual_desktop_msix_package_resource.go)
        according to `sdkPackage` in attached files and rules: 1. CRUD methods should
        be generated between `ResourceType` and `IDValidationFunc` methods. 2. `Update`
        method should come directly after `Create` method. 3. Timeout should be 30
        mins for `Create`, `Update`, and `Delete` methods and 5 mins for `Read` method.
        4. For `Optional` properties, check if properties are set before assigning
        to `param` structure in `Create` method. 5. For `Optional` `TypeInt` properties,
        use `metadata.ResourceDiff.GetRawConfig` method to check if properties are
        not null before assigning to `param` structure. 6. Instead of initialize `param`
        structure in `Update` method, use the model obtained from `client.Get` method.
        7. Do not include properties with `ForceNew` behavior in `Update` method.
        8. Only assign properties to `param` structure if `metadata.HasChange` method
        returns true for the properties in `Update` method. 9. Use `client.CreateOrUpdate`
        method instead of `client.Update` in `Update` method. 10. For `Optional` properties,
        only assign properties to `state` structure if the properties are returned
        by `client.Get` method in `Read` method. 11. Use `client` methods with polling
        whenever possible. 12. `expand` method should only be created when assigning
        more than 1 child property to a Go SDK parent property. 13. Do not expand
        Go SDK root level `Properties` structure. 14. `flatten` method should only
        be created to return a Terraform parent property in type of `interface` and
        more than 1 child property.'
    model: claude-sonnet-4.6
    nextStep: GenerateResourceIdentity
    type: copilot
  GenerateResourceIdentity:
    input:
    - prompt: Generate resource identity in [virtual_desktop_msix_package_resource.go](/home/v-yyeo/terraform-provider-azurerm-2/terraform-provider-azurerm/internal/services/desktopvirtualization/virtual_desktop_msix_package_resource.go).
        Use `pluginsdk.SetResourceIdentityData` method before returning in `Create`
        and `Read` methods. Add comment after `import` statement to generate resource
        identity test.
    model: claude-sonnet-4.6
    nextStep: RefactorFlatten
    type: copilot
  RefactorFlatten:
    input:
    - prompt: Wrap part of `Read` method in [virtual_desktop_msix_package_resource.go](/home/v-yyeo/terraform-provider-azurerm-2/terraform-provider-azurerm/internal/services/desktopvirtualization/virtual_desktop_msix_package_resource.go)
        from `state` initialization to `metadata.Encode` method (inclusive) in a separate
        `flatten` method. The `flatten` method should be located directly after `IDValidationFunc`
        method.
    model: claude-sonnet-4.6
    nextStep: ''
    type: copilot
